#
# Theme name: Muted Comfort;
# Description: Modern theme, with muted colors like gruvbox/everforest;
# Author: Lumanis45;

[colors.primary]
background =  '#0f0e0e'
foreground =  '#adadad'

[colors.normal]
black   = '#000000'
red     = '#a33f37'
green   = '#5fa337'
yellow  = '#bfad43'
blue    = '#3595c4'
magenta = '#af46bd'
cyan    = '#21bdbf'
white   = '#c7d1d1'

[colors.bright]
black   = '#282828'
red     = '#c9544d'
green   = '#73b858'
yellow  = '#cfbe53'
blue    = '#4faad6'
magenta = '#bf5ec9'
cyan    = '#3ccfd1'
white   = '#e0e0e0'
